--26ago21
--ALL DATABASE

-- EXEC  sp_help 'Tabela'

SELECT
	TOP 20 CONVERT(INT,
	(AVG_TOTAL_USER_COST * AVG_USER_IMPACT * (USER_SEEKS + USER_SCANS)) ) AS IMPACTO,
	MIGS.USER_SEEKS,
	MIGS.USER_SCANS,
	MID.STATEMENT,
	MID.EQUALITY_COLUMNS,
	MID.INEQUALITY_COLUMNS,
	MID.INCLUDED_COLUMNS
--	,MID.INDEX_HANDLE
FROM
	SYS.DM_DB_MISSING_INDEX_GROUP_STATS AS MIGS
JOIN SYS.DM_DB_MISSING_INDEX_GROUPS AS MIG ON
	MIGS.GROUP_HANDLE = MIG.INDEX_GROUP_HANDLE
JOIN SYS.DM_DB_MISSING_INDEX_DETAILS AS MID ON
	MIG.INDEX_HANDLE = MID.INDEX_HANDLE
	--  AND MID.STATEMENT LIKE '%TBNOTAFISCAL%'
ORDER BY
	IMPACTO DESC;