--25ago21

SELECT
	DB_NAME(ST.DBID) AS [DATABASE NAME],
	ST.[TEXT] AS [QUERY TEXT],
	WT.LAST_EXECUTION_TIME AS [LAST EXECUTION TIME],
	WT.EXECUTION_COUNT AS [EXECUTION COUNT],
	WT.TOTAL_WORKER_TIME / 1000000 AS [TOTAL CPU TIME(SECOND)],
	WT.TOTAL_WORKER_TIME / WT.EXECUTION_COUNT / 1000 AS [AVERAGE CPU TIME(MILISECOND)],
	QP.QUERY_PLAN
FROM
	(
	SELECT
		TOP 10 QS.LAST_EXECUTION_TIME,
		QS.EXECUTION_COUNT,
		QS.PLAN_HANDLE,
		QS.TOTAL_WORKER_TIME
	FROM
		SYS.DM_EXEC_QUERY_STATS QS
	ORDER BY
		QS.TOTAL_WORKER_TIME DESC) WT
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(PLAN_HANDLE) ST
CROSS APPLY SYS.DM_EXEC_QUERY_PLAN(PLAN_HANDLE) QP
ORDER BY
	WT.LAST_EXECUTION_TIME DESC
	-- WT.TOTAL_WORKER_TIME DESC