--06set21

--ALTER DATABASE
	--ALTER DATABASE dbSigaCELogos SET ONLINE;
	
	--ALTER DATABASE dbSigaLuizAntonio SET OFFLINE;

		--DROP DATABASE dbSigaSalesianoSaoJose_Arquivo05



--SINGLE_USER
	-- ALTER DATABASE [dbBibCELogos] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;

--MULTI_USER
	--	ALTER DATABASE [dbBibCELogos] SET  MULTI_USER WITH ROLLBACK IMMEDIATE;



--READ_WRITE
	-- ALTER DATABASE dbBibCELogos    SET  READ_WRITE WITH NO_WAIT

--READ_ONLY
	--ALTER DATABASE dbSigaSalesianoSaoJose_Arquivo    SET  READ_ONLY WITH NO_WAIT




--COLLATE SQL_Latin1_General_CP1_CI_AI
	--ALTER DATABASE dbCantinaTerceiroMilenio COLLATE SQL_Latin1_General_CP1_CI_AI;
