--06set21

--ALTER DATABASE
	--ALTER DATABASE dbSigaSalesianoSaoJose_Arquivo01 SET ONLINE;
	
	--ALTER DATABASE dbSigaSalesianoSaoJose_Arquivo01 SET OFFLINE;

		--DROP DATABASE dbSigaSalesianoSaoJose_Arquivo05



--SINGLE_USER
	-- ALTER DATABASE [dbLogMonitor] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;

--MULTI_USER
	--	ALTER DATABASE [dbSigaVicentinasRN] SET  MULTI_USER WITH ROLLBACK IMMEDIATE;



--READ_WRITE
	-- ALTER DATABASE dbActiveBibSaleJuvenal    SET  READ_WRITE WITH NO_WAIT

--READ_ONLY
	--ALTER DATABASE dbSigaSalesianoSaoJose_Arquivo    SET  READ_ONLY WITH NO_WAIT



--COLLATE SQL_Latin1_General_CP1_CI_AI
	--ALTER DATABASE dbCantinaTerceiroMilenio COLLATE SQL_Latin1_General_CP1_CI_AI;
