--25set21

--ONLINE
	--ALTER DATABASE SQL08_20210726_lixo SET ONLINE;
	
	--ALTER DATABASE SQL08_20210726_lixo SET OFFLINE;
                            

	--DROP
		--DROP DATABASE dbSigaRaizes



--SINGLE_USER & MULTI_USER
	--ALTER DATABASE [dbBibCELogos] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;

	--ALTER DATABASE [dbSigaMaisDomCursinho] SET  MULTI_USER WITH ROLLBACK IMMEDIATE;



--READ_WRITE & READ_ONLY
	--ALTER DATABASE dbSigaUniversoSaber    SET  READ_WRITE WITH NO_WAIT

	--ALTER DATABASE dbSigaCMT_Arquivo01    SET  READ_ONLY WITH NO_WAIT



--SET RECOVERY
	--ALTER DATABASE [dbSigaModuloAracaju_Arquivo01] SET RECOVERY SIMPLE WITH NO_WAIT;

	--ALTER DATABASE [dbBibCOLTIRADENTES] SET RECOVERY FULL WITH NO_WAIT



--ENABLE & DISABLE TRIGGER
	--DISABLE TRIGGER dbo.TgAudit_TbAlunoD ON dbo.TbAluno
	
	--ENABLE TRIGGER dbo.TgAudit_TbAlunoD  ON dbo.TbAluno



--sys.database_files
	-- USE dbSigaDiocCaruaru;
	-- SELECT file_id, name as [logical_file_name],physical_name from sys.database_files



--RESTORE FILELISTONLY
	-- RESTORE FILELISTONLY	FROM DISK = '/TEMP/bkp_dbSigaModuloAracaju_Arquivo01.bak'
	-- RESTORE FILELISTONLY	FROM DISK = 'C:\TEMP\dbSigaDiocesanoMossoro_backup_2021_11_15_220600_9714394.bak'

--RESTORE HEADERONLY
	--RESTORE HEADERONLY	FROM DISK = 'C:\Restore\dbSigaDiocesanoMossoro_backup_2021_11_15_220600_9714394.bak'




--COLLATE SQL_Latin1_General_CP1_CI_AI
	--ALTER DATABASE dbCantinaTerceiroMilenio COLLATE SQL_Latin1_General_CP1_CI_AI;
