SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON


CREATE TABLE dbo.TbAluno_Auditoria (
	[IdAlunoAuditoria] [bigint] IDENTITY(1,1) NOT NULL,
	[DataHora] [datetime] NOT NULL,
	[Operacao] [char](1) NOT NULL,
	[IdUsuario] [int] NULL,

	IdAluno int NULL,
	NomeAluno varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	NomeAbreviado varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IdUnidade int NULL,
	Matricula varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Senha char(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	CodigoLeitora varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Sexo char(1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	EstadoCivil char(1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	DataNascimento smalldatetime NULL,
	IdPai int NULL,
	IdMae int NULL,
	IdResponsavel int NULL,
	IdTipoResponsavel int NULL,
	Celular varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	SMS varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Email varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IdEndereco int NULL,
	CPF char(14) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	RG varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Naturalidade varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Nacionalidade varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TipoSangue char(3) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	PlanoSaude char(10) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Alergia varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Medicamento varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IdEstabelecimentoEnsinoAnterior int NULL,
	[_RegistroNascimento] varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TIAcodigo int NULL,
	IdReligiao int NULL,
	AnoConclusao varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	CorRaca char(1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	NaturalidadeCidade varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	NaturalidadeUF char(2) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	NumeroPasta varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IES_FormaIngresso char(1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IES_MediaVestibular numeric(5,2) NULL,
	IES_Curso char(2) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IES_AnoIngresso varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IES_SituacaoAluno char(2) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IES_DataSituacaoAluno smalldatetime NULL,
	RegistroNascimentoNumero varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	RegistroNascimentoLivro varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	RegistroNascimentoFolha varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	RegistroNascimentoCartorio varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IdentidadeEstudantil varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IdFormaEntregaDocumento int NULL,
	IdResponsavelSecundario int NULL,
	IdTipoResponsavelSecundario int NULL,
	RegistroNascimentoData smalldatetime NULL,
	IdentificadorCatraca int NULL,
	IdentidadeEstudantil_RU varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	Passaporte varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
--	[_IdentificadorMEC_Aluno] varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	StDeficienciaCegueira bit NULL,
	StDeficienciaBaixaVisao bit  NULL,
	StDeficienciaSurdez bit  NULL,
	StDeficienciaAuditiva bit  NULL,
	StDeficienciaFisica bit  NULL,
	StDeficienciaSurdoCegueira bit  NULL,
	StDeficienciaMultipla bit  NULL,
	StDeficienciaMental bit  NULL,
--	[_IdResponsavel_CadastroVinculado] int NULL,
	NumeroNIS varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	CodigoINEP varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TipoNacionalidade char(1) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	IdPaisOrigem int NULL,
	RG_OrgaoEmissor varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	RG_DataEmissao smalldatetime NULL,
	StMatriculaTemp bit  NULL,
	GpaIdentificadorCatraca varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GpaDataHoraAlteracao datetime DEFAULT getdate() NULL,
	IdAluno_CadastroVinculadoOrigem int NULL,
	GpaIdentificadorCatraca2 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GpaIdentificadorCatraca3 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GpaIdentificadorCatraca4 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GpaIdentificadorCatraca5 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	StFalecido bit  NULL,
	TituloEleitor_Numero varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TituloEleitor_DataExpedicao smalldatetime NULL,
	TituloEleitor_Cidade varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TituloEleitor_UF varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TituloEleitor_Secao varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TituloEleitor_Zona varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	TituloEleitor_StQuitacaoEleitoral bit NULL,
	EnsinoMedio_IdEstabelecimentoEnsino int NULL,
	EnsinoMedio_AnoConclusao varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	CertidaoReservista varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	RG_OrgaoEmissorUF char(2) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	StDeficienciaAutismoInfantil bit  NULL,
	StDeficienciaSindromeAsperger bit  NULL,
	StDeficienciaSindromeRett bit  NULL,
	StDeficienciaTrastornoDesintegrativo bit  NULL,
	StDeficienciaAltasHabilidades bit  NULL,
	GoogleForEducation_Id varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GoogleForEducation_Email varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GoogleForEducation_Nome varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GoogleForEducation_SobreNome varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	NomeCivil varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	GoogleForEducation_LogProcessamento varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	StAppComunicacao_Sincronizado bit  NULL,
	AppComunicacao_LogProcessamento varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AI NULL,
	CONSTRAINT PK_TbAluno_Auditoria PRIMARY KEY CLUSTERED  
(
	[IdAlunoAuditoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];




