-- 03ago21

-- backup-migracao-diff
	-- SQl07 -> SQL09
    -- VPS8

-- DECLARE @Database			VARCHAR(32) = 'dbSiga'
 
 BEGIN TRY
	SELECT  'SET SINGLE_USER'   

	-- ALTER DATABASE [dbSigaFACHO]    SET  READ_WRITE WITH NO_WAIT;
	-- ALTER DATABASE [dbSigaFACHO] SET  MULTI_USER WITH ROLLBACK IMMEDIATE;

    ALTER DATABASE [dbSigaFACHO] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;  
    

	USE [dbSigaFACHO]; 
	USE [master]; 

	SELECT DB_NAME();

    IF EXISTS( SELECT * FROM sys.databases WHERE NAME = 'dbSigaFACHO' AND user_access_desc = 'SINGLE_USER' )
	BEGIN
		-- *_Arquivo01...
       	INSERT INTO [dbSigaFACHO].[dbo].[TbAuditoria] ([Tabela],[Operacao],[DescricaoOperacao], [Datahora]) VALUES ('TbAuditoria', 'I','REGISTRO DE MIGRACAO DE SERVIDOR', GETDATE());
       	-- INSERT INTO [dbSigaFACHO].[dbo].[TbAuditoria] ([Tabela],[Operacao],[DescricaoOperacao]) VALUES ('TbAuditoria', 'I','REGISTRO DE MIGRACAO DE SERVIDOR');


		IF EXISTS( SELECT TOP 1 * FROM [dbSigaFACHO].[dbo].[TbAuditoria] WHERE [DescricaoOperacao] LIKE 'REGISTRO DE MIGRACAO DE SERVIDOR' ORDER BY DataHora DESC )
		BEGIN
			SELECT 'REGISTRO DE MIGRACAO DE SERVIDOR'
			-- BACKUP DATABASE [dbSigaFACHO] TO  DISK = 'C:\TEMP\dbSigaFACHO_diff.bak' WITH FORMAT, INIT, NAME = 'dbSigaFACHO-diff', SKIP, NOREWIND, NOUNLOAD, DIFFERENTIAL, STATS = 100;
		END


		SELECT 'SET OFFLINE'
		ALTER DATABASE [dbSigaFACHO] SET  OFFLINE WITH ROLLBACK IMMEDIATE;
		-- ALTER DATABASE [dbSigaFACHO] SET  ONLINE WITH ROLLBACK IMMEDIATE;
	END
END TRY
    BEGIN CATCH
       PRINT ERROR_MESSAGE();
    END CATCH



-- ATENCAO
--	VPS WINDOWS -- FAZER UPLOAD DO BACKUP .DIF VIA LINHA DE COMANDO USANDO SCRIPT GERADO AUTOMATICAMENTE.